rcl_logging_log4cxx/CMakeLists.txt

Fixes issue [#5](https://github.com/ros2/rcl_logging/issues/5). This enables compiling ROS2 with log4cxx (by setting RCL_LOGGING_IMPLEMENTATION to rcl_logging_log4cxx).

Added include dir to installation of rcl_logging_log4cxx.

---

rcl_logging_log4cxx/CMakeLists.txt
rcl_logging_log4cxx/src/rcl_logging_log4cxx/rcl_logging_log4cxx.cpp
rcl_logging_noop/CMakeLists.txt

During the review of this PR: https://github.com/ros2/rcl/pull/425 we found that there were permission issues with writing to /var/log. The quick fix for this is to use the same behavior that we have on Windows, which is to log to a local directory instead.

Changing the default location for log files to be a local directory instead of /var/log/ros on linux due to permission issues.

---

rcl_logging_spdlog/CMakeLists.txt
rcl_logging_spdlog/include/rcl_logging_spdlog/logging_interface.h
rcl_logging_spdlog/include/rcl_logging_spdlog/visibility_control.h
rcl_logging_spdlog/package.xml
rcl_logging_spdlog/src/rcl_logging_spdlog.cpp

Along with ros2/rcutils#166 and ros2/rcl#466, this PR is one way we could implement per-process logging in ROS 2.  It uses a header-only C++ library called [spdlog](https://github.com/gabime/spdlog) instead of log4cxx (which has a bunch of problems).  I'm not at all tied to using this library, but it is relatively straightforward and has most of the features we want.  The open questions with this PR (in rough order of priority):
1.  Is spdlog good enough for our purposes?  It supports all of the features of log4cxx that we were using, with the exception of external configuration.  It just doesn't have a way to be configured from a file.  We could define something, we could ignore the feature, or we could find another C++ logging library that has that feature.
1.  When running a simple …

Implement a backend logger using spdlog.

---

rcl_logging_spdlog/CMakeLists.txt

Remove it here.  This should allow downstream packages to
build properly.

spdlog is a header-only library, so the exported dep isn't needed.

---

rcl_logging_spdlog/src/rcl_logging_spdlog.cpp

See warning: https://ci.ros2.org/job/ci_osx/6754/warnings11Result/
macOS: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6758)](https://ci.ros2.org/job/ci_osx/6758/)

Fix Clang warning about possible uninitialized variable

---

rcl_logging_log4cxx/src/rcl_logging_log4cxx/rcl_logging_log4cxx.cpp
rcl_logging_spdlog/src/rcl_logging_spdlog.cpp

Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.

code style only: wrap after open parenthesis if not in one line

---

rcl_logging_spdlog/CMakeLists.txt
rcl_logging_spdlog/package.xml

Newer spdlog (>= 1.5.0) builds a shared library, so we
need to add an exec_depend now.
Part of solving https://github.com/ros2/rcl_logging/issues/26

Make spdlog an exec_depend.

---

rcl_logging_log4cxx/CMakeLists.txt
rcl_logging_noop/CMakeLists.txt

When invoking CMake with `--warn-uninitialized`.

fix CMake warning about using uninitialized variables

---

rcl_logging_spdlog/CMakeLists.txt

export targets in a addition to include directories / libraries

---

CONTRIBUTING.md
README.md
rcl_logging_spdlog/Quality_Declaration.md
rcl_logging_spdlog/README.md

This PR adds the current Quality Declaration claim for the rcl_logging_spdlog package. The current state is Quality level 4.
It will also add Contributing.md file to properly document License contributions and Readme pointing to current Quality Declaration.
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

Current state Quality Declaration, Contributing and Readme files

---

rcl_logging_log4cxx/include/rcl_logging_log4cxx/logging_interface.h
rcl_logging_spdlog/include/rcl_logging_spdlog/logging_interface.h

In combination with ros2/rcl#652.

warn about unused return value for set_logger_level

---

rcl_logging_spdlog/CMakeLists.txt
rcl_logging_spdlog/test/test_logging_interface.cpp

Eventually we'll want to create a test to verify that we have spdlog configured correctly and can log data, but right now there aren't any good mechanisms to keep us from showering the `~/.ros/log/` directory with our log files. There also isn't a great way to determine exactly where the log ended up.
I'll follow-up with changes to add more comprehensive testing when those mechanisms are available.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10754)](http://ci.ros2.org/job/ci_linux/10754/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6149)](http://ci.ros2.org/job/ci_linux-aarch64/6149/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8756)](http://ci.ros2.org/job/ci_osx/8756/ …

Add some preliminary functional tests

---

rcl_logging_spdlog/CMakeLists.txt
rcl_logging_spdlog/package.xml
rcl_logging_spdlog/test/fixtures.hpp
rcl_logging_spdlog/test/test_logging_interface.cpp

As suggested in [#36 (comment)](https://github.com/ros2/rcl_logging/pull/36#issuecomment-629144007), some of this approach takes after #37.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11021)](http://ci.ros2.org/job/ci_linux/11021/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6353)](http://ci.ros2.org/job/ci_linux-aarch64/6353/)
* Linux-coverage [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11021)](http://ci.ros2.org/job/ci_linux/11021/cobertura/src_ros2_rcl_logging_rcl_logging_spdlog_src/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8978)](http://ci.ros2.org/job/ci_osx/8978/)
* Windows [![Build …

More spdlog tests

---

rcl_logging_log4cxx/package.xml
rcl_logging_noop/package.xml

Neither log4cxx nor the noop backends use the pytest dependency,
so remove it.
This is somewhat related to ros2/ros2#951, but is really just something I noticed while debugging that. CI is over in that other issue.

Remove unused pytest dependency.

---

rcl_logging_spdlog/Doxyfile
rcl_logging_spdlog/QUALITY_DECLARATION.md
rcl_logging_spdlog/README.md

[foxy backport] Added Doxyfile and fixed related warnings (#42)

---

rcl_logging_log4cxx/include/rcl_logging_log4cxx/logging_interface.h
rcl_logging_spdlog/include/rcl_logging_spdlog/logging_interface.h

While running the ABI tool on the package the compilation of the headers displays a problem unable to found [`rcutils_allocator_t` in logging_interface.h](https://github.com/ros2/rcl_logging/compare/foxy...jrivero/missing_allocator_header_foxy?expand=1#diff-09665547ad7117bc6bfca31abb0cf87aR43). I think we are missing the include in the file.

Include rcutils/allocator.h in logging_interface.h

---

rcl_logging_spdlog/test/test_logging_interface.cpp

Removed TODO 
Compiling up-to `rcl_logging_spdlog` and testing `rcl_logging_spdlog` becuse this change only affect the spdlog test.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12339)](http://ci.ros2.org/job/ci_linux/12339/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7308)](http://ci.ros2.org/job/ci_linux-aarch64/7308/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10052)](http://ci.ros2.org/job/ci_osx/10052/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12248)](http://ci.ros2.org/job/ci_windows/12248/)
Signed-off-by: ahcorde <ahcorde@gmail.com>

Used current_path() function from rcpputils

---

rcl_logging_interface/src/logging_dir.c

Follow-up to #53, now that `rcutils_expand_user` has been added (https://github.com/ros2/rcutils/pull/298).

Use rcutils_expand_user() in rcl_logging_get_logging_directory()

---

rcl_logging_spdlog/CMakeLists.txt

This PR enables `-Wformat=2`, `-Wconversion`, `-Woverloaded-virtual`, `-Wshadow`, `-Wnon-virtual-dtor`, `-Wold-style-cast`, and `-Wcast-qual` in `rcl_logging_spdlog`. No source code was modified to enable these warnings.
Relies on `googletest` being v1.10.0 (https://github.com/ament/googletest/pull/8).

[rcl_logging_spdlog] Add warnings

---

rcl_logging_noop/CMakeLists.txt
rcl_logging_spdlog/CMakeLists.txt

`rcpputils`, `rcutils`, and `spdlog` don't need to be exposed to downstream users of this package at their build time because these dependencies are only used internally.
I think `rcl_logging_interface` should still be exposed because this package only appears to be useful if one has those headers, but that won't affect how this is currently used downstream because `rcl` [already depends on both](https://github.com/ros2/rcl/blob/e9c87e279bf7509c940b87fd4d6c5dff301bc735/rcl/package.xml#L19-L20) and has [custom CMake logic to `find_package()` it](https://github.com/ros2/rcl/blob/e9c87e279bf7509c940b87fd4d6c5dff301bc735/rcl/CMakeLists.txt#L18).
Fixes #58 
Uses `target_link_libraries()` because all of its dependencies are using targets already ament/ament_cmake#292

Make internal dependencies private

---

rcl_logging_spdlog/test/benchmark/benchmark_logging_interface.cpp

Pointed out by clang static analysis as a dead store.

Make sure to check return value from external_initialize.

---

rcl_logging_spdlog/CMakeLists.txt
rcl_logging_spdlog/include/rcl_logging_spdlog/logging_interface.h
rcl_logging_spdlog/package.xml
rcl_logging_spdlog/src/rcl_logging_spdlog.cpp
rcl_logging_spdlog/test/test_logging_interface.cpp

Backport of functionality from PR Allow configuring logging directory through environment variables #53. 
This allows configuring the logging directory through environment variables using the following logic:
Use $ROS_LOG_DIR if ROS_LOG_DIR is set and not empty.
Otherwise, use $ROS_HOME/log, using ~/.ros for ROS_HOME if not set or if empty.
Implemented only for spd log. 
Should it also be added for log4cxx? If so, should a copy of the rcl_logging_get_logging_directory API be added to the log4cxx package?

[Foxy] Allow configuring logging directory through environment variables

---

rcl_logging_spdlog/test/fixtures.hpp

MAX_PATH is defined in `windows.h` and after https://github.com/ros2/rcpputils/pull/118 is not being automatically included by `rcpputils/filesystem_helper.hpp` anymore.

Include what you use

---

rcl_logging_spdlog/QUALITY_DECLARATION.md

Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52

Updating Quality Declaration

---

rcl_logging_interface/src/logging_dir.c
rcl_logging_log4cxx/src/rcl_logging_log4cxx/rcl_logging_log4cxx.cpp
rcl_logging_spdlog/src/rcl_logging_spdlog.cpp
rcl_logging_spdlog/test/fixtures.hpp

https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.
Note that in some cases I simply removed the `#include` since nothing from that header was actually used.

Update includes after rcutils/get_env.h deprecation

---

rcl_logging_log4cxx/CMakeLists.txt

The newest version of `log4cxx` on macOS is now built with C++17 on homebrew (the expected way to install the package, based on the ROS2 installation guide). C++17 adds support for `shared_mutex`, so `log4cxx` defaults to using `shared_mutex` in `std` instead of `boost`. C++14, however, doesn't have `shared_mutex`, so building `rcl_logging_log4cxx` on macOS with the latest packages now fails because it uses C++14. The easiest way to fix this is to switch this package to build on C++17, which is what I've done here. 
If you all have any other solutions to this issue feel free to propose them, but this is the simplest one I could come up with, and is imperative for all macOS ROS2 users building from source.

macOS build fix

---

rcl_logging_interface/Doxyfile

Precisely what the title says. This configuration gets `rosdoc2` documentation builds going.

Add Doxyfile to rcl_logging_interface package.

---

rcl_logging_interface/test/test_get_logging_directory.cpp
rcl_logging_spdlog/test/test_logging_interface.cpp

`rcpputils/get_env.hpp` is renamed to `rcpputils/env.hpp` as part of https://github.com/ros2/rcpputils/pull/150, so the corresponding includes have been fixed in this PR.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

Fix renamed `rcpputils` header

---

rcl_logging_log4cxx/CMakeLists.txt

Signed-off-by: Homalozoa <xuhaiwang@xiaomi.com>
Fix building error with log4cxx 0.12.0. shared_mutex is only available from C++ 17 onwards, ref: [std::shared_mutex](https://en.cppreference.com/w/cpp/thread/shared_mutex)
```
-- stderr: rcl_logging_log4cxx                                                                                                                                                                                         
In file included from /usr/include/log4cxx/log4cxx.h:45,
from /usr/include/log4cxx/logstring.h:28,
from /usr/include/log4cxx/spi/appenderattachable.h:26,
from /usr/include/log4cxx/helpers/appenderattachableimpl.h:27,
from /usr/include/log4cxx/logger.h:30,
from /home/homalozoa/local_git/ros2_fork/src/ros2/rcl_logging/rcl_logging_log4cxx/src/rcl_logging_log4cx …
```

Change C++ version to 17 in `rcl_logging_log4cxx`

---

rcl_logging_interface/CMakeLists.txt

Part of ros2/ros2#1150 - This eliminates issues with the include directory search order when overriding these packages by installing their includes to `include/${PROJECT_NAME}`

Install includes to include/${PROJECT_NAME}

---

rcl_logging_spdlog/CMakeLists.txt

Resolves #82 
When building static libraries [CMake will link PRIVATE targets downstream as if they were PUBLIC](https://cmake.org/pipermail/cmake/2016-May/063400.html). This calls `ament_export_dependencies` on all packages providing targets that are linked against so downstream packages have those targets available too.

ament_export_dependencies any package with targets we linked against

---

rcl_logging_spdlog/CMakeLists.txt

Disable cppcheck for rcl_logging_spdlog.

---

rcl_logging_interface/CMakeLists.txt
rcl_logging_noop/CMakeLists.txt
rcl_logging_spdlog/CMakeLists.txt

The two reasons to do this are:
1. So that we can compile rcl_logging with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
2. So we can build with a newer version of gtest which requires this.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.

Update rcl_logging to C++17.

---

rcl_logging_spdlog/test/benchmark/benchmark_logging_interface.cpp

This just makes clang happier.

Mark the benchmark _ as unused.

---

rcl_logging_spdlog/test/test_logging_interface.cpp

We're not very strict about includes, but I noticed a slight divergence as a result of https://github.com/ros2/rcl_logging/pull/41

Re-order rcl_logging_interface include

---

rcl_logging_spdlog/QUALITY_DECLARATION.md

* Switch from "ROS2" to "ROS 2"
* Update branch name in links (`/master/` -> `/rolling/`)
* Apply one-sentence-per-line rule in some places

Update quality declaration document

---

rcl_logging_interface/include/rcl_logging_interface/rcl_logging_interface.h

Some more picky linters report it, but in any case we do this in most (if not all) of ROS 2's C `.h` files.

Use (void) in declaration of param-less function

---

rcl_logging_interface/src/logging_dir.c
rcl_logging_spdlog/src/rcl_logging_spdlog.cpp
rcl_logging_spdlog/test/test_logging_interface.cpp

If the allocator is zero-initialized, it may cause a segfault when it is used later in the function. Right now, we're relying on other `rcutils_*` functions which use the allocator to fail before we attempt to use it directly, but just because the allocator is passed to these functions doesn't always mean that it is used, especially when the program flow can change based on things like environment variables.

Check allocator validity in some rcl_logging functions

---

rcl_logging_noop/CMakeLists.txt
rcl_logging_spdlog/CMakeLists.txt

closes https://github.com/ros2/rcl_logging/issues/121

rcl_logging_interface is only valid path with build environment.
